image: "node:12.13.0"

stages:
  - test
  - build
  - dockerize
  - push
  - deploy

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm test

build_react:
  stage: build
  before_script:
    - npm install
  script:
    - npm run-script build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

build_ngnix_container:
  stage: dockerize
  image: "docker:20.10"
  dependencies:
    - build_react

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:20.10-dind

  script:
    - docker buildx create --use
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker buildx build  --platform linux/arm/v7,linux/arm64/v8 --pull --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --push .

tag_master:
  stage: push
  image: "docker:19.03.3"
  dependencies:
    - build_react
  only:
    - master

  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    GIT_STRATEGY: none

  services:
    - docker:19.03.3-dind

  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
