image: "node:alpine"

stages:
  - test
  - build
  - deploy

before_script:
  - npm install

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run-script build
  artifacts:
    paths: build/
    expire_in: 1 week
